server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: root

mybatis:
  type-aliases-package: com.yangyong.swjtu.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.yangyong.swjtu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

